"""Parser for PDB files generated by processPDBwithH.pl."""

from numpy import array
from Chain import Chain
from Residue import Residue
from Atom import Atom

class PerlGenPDBParser:
    """
    Parse a PDB file generated by and return a Chain object.
    """

    def __init__(self, filename):
        assert(isinstance(filename, str))
        self.__chain = self.__current_residue = None
        self._parse_coordinates(open(filename).readlines())

    def get_chain(self):
        return self.__chain

    def _parse_coordinates(self, lines):
        self.__chain = Chain(lines[0].split()[4])

        for i in range(len(lines)):
            items = lines[i].split()

            atom_serial_num = int(items[1])
            atom_name = items[2]
            element = lines[i][13]
            residue_name = items[3]
            residue_serial_num = int(items[5])
            coords =  array([items[6], items[7], items[8]], 'f')
            
            if self.__current_residue is None or self.__current_residue.sequence_number() != residue_serial_num:
                self.__current_residue = Residue(residue_serial_num, residue_name)
                self.__chain.add_residue(self.__current_residue)

            self.__current_residue.add_atom(Atom(atom_serial_num, atom_name, coords, element))